### ISSUE TITLE
Problem with GCMCore

### ISSUE THREAD

**Issue by jan-schaeffer** [CorrelAid/git-newbie-playground#2]
Hi Frie,

currently trying this on my M1 MBA with Git 2.32.0 (Apple Git-132) already pre-installed.

Followed all steps up to: 
`git config --global credential.helper manager-core`

This then gives me:
```
warning: credential.helper has multiple values
error: cannot overwrite multiple values with a single value
       Use a regexp, --add or --replace-all to change credential.helper.
```

I moved on to cloning the git-tryout repo (which worked) but it did not give me the dialogue mentioned in 4.2.2, hence I could not enter the PAT.

**Comment by jan-schaeffer** [comment]
Quick update: 

I followed this tutorial: https://medium.com/codex/git-authentication-on-macos-setting-up-ssh-to-connect-to-your-github-account-d7f5df029320

Then when cloning the repo it asked for the PAT.

Seems to be working fine now!

**Comment by pr130** [comment]
@jan-schaeffer thanks for the feedback :) will integrate that !
